### ISSUE TITLE
Problem with downloading tiff-4.0.4beta.tar.gz

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#103]
I have problem with downloading 4.0.4beta.tar.gz.

phracek@kiasportyw-brq-redhat-com: ~/work/Fedora/libtiff (master %)$ rebase-helper 4.0.4beta
Downloading sources from URL ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.4.tar.gz
Traceback (most recent call last):
  File "/home/phracek/work/programming/rebase-helper/rebase-helper.py", line 28, in <module>
    sys.exit(CliHelper.run())
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/cli.py", line 131, in run
    app = Application(cli)
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/application.py", line 90, in __init__
    self._prepare_spec_objects()
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/application.py", line 142, in _prepare_spec_objects
    self.rebase_spec_file.set_version(version)
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/specfile.py", line 738, in set_version
    self.save()
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/specfile.py", line 871, in save
    self._update_data()
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/specfile.py", line 136, in _update_data
    self.sources = self._get_initial_sources_list()
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/specfile.py", line 155, in _get_initial_sources_list
    DownloadHelper.download_file(src[0], abs_path)
  File "/home/phracek/work/programming/rebase-helper/rebasehelper/utils.py", line 153, in download_file
    raise ReferenceError("Downloading '%s' failed with error '%s'.", url, error)
ReferenceError: ("Downloading '%s' failed with error '%s'.", 'ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.4.tar.gz', error(78, 'RETR response: 550'))
phracek@kiasportyw-brq-redhat-com: ~/work/Fedora/libtiff (master %)$

**Comment by phracek** [comment]
#192
