### ISSUE TITLE
'Summary information about patches' crashes

### ISSUE THREAD

**Issue by jpopelka** [phracek/rebase-helper#107]
Traceback (most recent call last):
  File "/home/jpopelka/git/rebase-helper/rebase-helper.py", line 28, in <module>
    sys.exit(CliHelper.run())
  File "/home/jpopelka/git/rebase-helper/rebasehelper/cli.py", line 132, in run
    app.run()
  File "/home/jpopelka/git/rebase-helper/rebasehelper/application.py", line 423, in run
    self.print_summary()
  File "/home/jpopelka/git/rebase-helper/rebasehelper/application.py", line 404, in print_summary
    output.print_information(path=self._get_rebase_helper_log())
  File "/home/jpopelka/git/rebase-helper/rebasehelper/output_tool.py", line 196, in print_information
    return self._tool.print_summary(path)
  File "/home/jpopelka/git/rebase-helper/rebasehelper/output_tool.py", line 155, in print_summary
    cls.print_patches(OutputLogger.get_patches(), '\nSummary information about patches:')
  File "/home/jpopelka/git/rebase-helper/rebasehelper/output_tool.py", line 93, in print_patches
    max_name = max([len(os.path.basename(x)) for y in six.itervalues(patches) for x in y])
ValueError: max() arg is an empty sequence

Was trying to rebase cups-filters (to 1.0.69) in Fedora

**Comment by phracek** [comment]
This is fixed by commit https://github.com/phracek/rebase-helper/commit/63584ed5c8700322e3345baeb4dd8a4c71034926
