### ISSUE TITLE
provide some sain message when 'koji' module is not present and ideally fall back to mockbuild

### ISSUE THREAD

**Issue by thozza** [phracek/rebase-helper#116]
When running rebase-helper without 'koji' module installed, it ends with traceback. It would be nice to provide some nice error message and ideally fall-back to some working method for building RPM, like mockbuild.

**Comment by thozza** [comment]
```
$ python3 ~/devel/projects/rebase-helper/rebase-helper.py -h 
Traceback (most recent call last):
  File "/home/thozza/devel/projects/rebase-helper/rebase-helper.py", line 25, in <module>
    from rebasehelper.cli import CliHelper
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/cli.py", line 27, in <module>
    from rebasehelper.application import Application
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py", line 35, in <module>
    from rebasehelper.build_helper import Builder, SourcePackageBuildError, BinaryPackageBuildError
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/build_helper.py", line 25, in <module>
    import koji
ImportError: No module named 'koji'
```
The issue may be the Python3
