### ISSUE TITLE
rebase-helper fails in case of macros used in SPEC file

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#140]
Downloaded sources failed because of https://github.com/rcaelers/workrave/archive/**%{commit}**/workrave-1.10.tar.gz
~~~
[2015-12-01 08:02:43][    fedmsg    INFO] RebaseHelper package workrave
[2015-12-01 08:02:43][    fedmsg    INFO] RebaseHelper upstream version v1_10_8
[2015-12-01 08:02:43][    fedmsg    INFO] RebaseHelper old version 1.10
No handlers could be found for logger "rebase-helper-upstream"
Downloading sources from URL https://github.com/rcaelers/workrave/archive/%{commit}/workrave-1.10.tar.gz
['--non-interactive', '--buildtool', 'fedpkg', '1.10']
[2015-12-01 08:02:43][    fedmsg WARNING] Failed to kick off scratch build.
[2015-12-01 08:02:43][    fedmsg WARNING] Traceback (most recent call last):
  File "/root/the-new-hotness/hotness/consumers.py", line 256, in _handle_anitya_update
    package, upstream, version, bz)
  File "/root/the-new-hotness/hotness/buildsys.py", line 100, in handle
    ret_code, rh_stuff = ret_val = rh_upstream.process_thn()
  File "/usr/lib/python2.7/site-packages/rebasehelper/upstream_monitoring.py", line 217, in process_thn
    self.result_rh = self._call_rebase_helper()
  File "/usr/lib/python2.7/site-packages/rebasehelper/upstream_monitoring.py", line 131, in _call_rebase_helper
    self.result_rh = rh_app.run()
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 503, in run
    sources = self.prepare_sources()
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 333, in prepare_sources
    os.path.join(self.execution_dir, settings.OLD_SOURCES_DIR))
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 304, in extract_sources
    Application.extract_archive(archive_path, destination)
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 293, in extract_archive

~~~

**Comment by nforro** [comment]
I'm not sure what you mean by "RPM definition", but looking at the spec file it seems that the only way how to build the workrave package is to pass commit hash as an argument to rpmbuild, because the %{commit} macro is not defined anywhere.
However, even if the macro was defined in the spec file, IMHO it wouldn't work, because rebase-helper wouldn't be able to parse version number from "v1_10_8".

**Comment by phracek** [comment]
It seems to be bug in SPEC file. Closing it.
