### ISSUE TITLE
got traceback when I tried it for the first time

### ISSUE THREAD

**Issue by TomasTomecek** [phracek/rebase-helper#176]
I have no idea what it should do:
```
$ rebase-helper ./docker-py-b98e24095894d6a7a667b3c978ede2e92598db71.tar.gz
Traceback (most recent call last):
  File "/bin/rebase-helper", line 9, in <module>
    load_entry_point('rebasehelper==0.7.3', 'console_scripts', 'rebase-helper')()
  File "/usr/lib/python2.7/site-packages/rebasehelper/cli.py", line 147, in run
    app = Application(cli)
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 102, in __init__
    self._prepare_spec_objects()
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 170, in _prepare_spec_objects
    self.rebase_spec_file.set_version_using_archive(self.conf.sources)
  File "/usr/lib/python2.7/site-packages/rebasehelper/specfile.py", line 869, in set_version_using_archive
    self.set_version(version)
  File "/usr/lib/python2.7/site-packages/rebasehelper/specfile.py", line 783, in set_version
    self.spec_content[index] = line.replace(match.group(1), version)
TypeError: expected a character buffer object
```
This is fedora package `python-docker-py`, master branch, commit `4b12583a1b106ec82aa8d6e45ed367eb0f84b545` if you want a reproducer.

Installed from fedora 22 stable repos.

**Comment by nforro** [comment]
Problem is that the tarball filename doesn't contain version, so *rebase-helper* can't detect it and fails.
Of course it shouldn't traceback, but print some meaningful error message instead.

Bigger problem is that the *Source0* URL doesn't contain `%{version}` macro, so it stays the same after the *Version* tag is modified. So even if you would specify the version directly, *rebase-helper* wouldn't be able to rebase the package. I'll open separate issue for that.

**Comment by TomasTomecek** [comment]
the fix should work, thanks!
