### ISSUE TITLE
would be nice to improve error checking and reporting

### ISSUE THREAD

**Issue by pavlix** [phracek/rebase-helper#88]
Applying patch failed. Starting merge-tool to fix conflicts manually.
    Traceback (most recent call last):
      File "/usr/lib/python-exec/python2.7/rebase-helper", line 9, in <module>
        load_entry_point('rebasehelper==0.4.0', 'console_scripts', 'rebase-helper')()
      File "/usr/lib64/python2.7/site-packages/rebasehelper/cli.py", line 129, in run
        app.run()
      File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 417, in run
        self.patch_sources(sources)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 312, in patch_sources
        **self.kwargs)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/patch_helper.py", line 307, in patch
        return self._tool.run_patch(old_dir, new_dir, patches, rebased_patches, **kwargs)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/patch_helper.py", line 265, in run_patch
        patch = cls.apply_patch(cls.rebased_patches[order[0]])
      File "/usr/lib64/python2.7/site-packages/rebasehelper/patch_helper.py", line 235, in apply_patch
        patch[0] = cls.execute_diff_helper(patch)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/patch_helper.py", line 152, in execute_diff_helper
        patched_files = cls.get_failed_patched_files(patch[0])
      File "/usr/lib64/python2.7/site-packages/rebasehelper/patch_helper.py", line 121, in get_failed_patched_files
        output=output)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/utils.py", line 163, in run_subprocess_cwd
        return ProcessHelper.run_subprocess_cwd_env(cmd, cwd=cwd, input=input, output=output, shell=shell)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/utils.py", line 260, in run_subprocess_cwd_env
        shell=shell)
      File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

How's one supposed to learn that we miss a runtime dependency, patchutils in this case? Might be good to test for all the tools right when the tool is started and possibly run the tools through some wrapper function that would report what exactly is wrong.

**Comment by thozza** [comment]
Thank you for the report. We should definitely list the dependencies in the README file. In Fedora dependencies are resolved by the RPM, but if using from git, one can not know what needs to be installed.

**Comment by phracek** [comment]
I have closed wrong issue. Reopen it.

**Comment by phracek** [comment]
Currently, we have changed the rebase workflow from patch command to git rebased.
We have to detected somehow if meld is not installed.
E.g. if meld is not installed then git has to fail. Currently now it waits and tries to execute meld which is not installed.

I don't have an idea how to do it, though.
