### ISSUE TITLE
yet another cryptic traceback

### ISSUE THREAD

**Issue by pavlix** [phracek/rebase-helper#90]
I have not yet analyzed what's wrong here. This happens after all the meld patch merging work.

    Building SRPM
    cmd=['mock', '--buildsrpm', '--spec', '/tmp/rebase-helper-Zm6To5/SPECS/squid.spec', '--sources', '/tmp/rebase-helper-Zm6To5/SOURCES', '--resultdir', '/tmp/rebase-helper-Zm6To5/RESULTS'], cwd=None, env=None, input=None, output=/tmp/rebase-helper-Zm6To5/RESULTS/mock_output.log, shell=False
    Copying 'log' '/tmp/rebase-helper-Zm6To5/RESULTS/mock_output.log' to '/home/pavlix/rhel/squid/rebase-helper-results/old/SRPM'
    Exit callback executed successfully
    Destroyed environment in '/tmp/rebase-helper-Zm6To5'
    Traceback (most recent call last):
      File "/usr/lib/python-exec/python2.7/rebase-helper", line 9, in <module>
        load_entry_point('rebasehelper==0.4.0', 'console_scripts', 'rebase-helper')()
      File "/usr/lib64/python2.7/site-packages/rebasehelper/cli.py", line 129, in run
        app.run()
      File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 424, in run
        self.build_packages()
      File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 343, in build_packages
        build_dict.update(builder.build(spec, sources, patches, results_dir, **build_dict))
      File "/usr/lib64/python2.7/site-packages/rebasehelper/build_helper.py", line 465, in build
        return self._tool.build(*args, **kwargs)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/build_helper.py", line 242, in build
        srpm = cls._build_srpm(tmp_spec, tmp_sources_dir, tmp_results_dir)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/build_helper.py", line 183, in _build_srpm
        ret = ProcessHelper.run_subprocess(cmd, output=output)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/utils.py", line 149, in run_subprocess
        return ProcessHelper.run_subprocess_cwd(cmd, input=input, output=output)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/utils.py", line 163, in run_subprocess_cwd
        return ProcessHelper.run_subprocess_cwd_env(cmd, cwd=cwd, input=input, output=output, shell=shell)
      File "/usr/lib64/python2.7/site-packages/rebasehelper/utils.py", line 260, in run_subprocess_cwd_env
        shell=shell)
      File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

No idea what got wrong, no real error reporting or hints. Using rebase-helper from git master. This happened when all the human hard work is done but there's no information on how to recover.
    
This following worked for me:
    
    mv rebase-helper-results/* .

Then I only have to manually remove obsolete patches (they're listed and commented out in the spec file) and we seem to be done except minor tweaks of the spec file, right?

**Comment by phracek** [comment]
What command did you use for rebasing? Do you have installed mock?

**Comment by phracek** [comment]
On main page are mentioned dependencies. Git rebase is used now instead of patch command
