### ISSUE TITLE
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by thozza** [phracek/rebase-helper#93]
Running rebase-helper for wget ends with traceback:
```
$ python3 ~/devel/projects/rebase-helper/rebase-helper.py 1.16.3
Results directory 'rebase-helper-results' exists, removing it
Downloading sources from URL ftp://ftp.gnu.org/gnu/wget/wget-1.16.3.tar.xz
Workspace directory 'rebase-helper-workspace' exists, removing it
Applying patch 'wget-rh-modified.patch' to 'wget-1.16.2'
Applying patch 'wget-1.16.1-path.patch' to 'wget-1.16.2'
Applying patch 'wget-1.16-dont-run-failing-test.patch' to 'wget-1.16.2'
Rebase operation is ongoing...
Traceback (most recent call last):
  File "/home/thozza/devel/projects/rebase-helper/rebase-helper.py", line 28, in <module>
    sys.exit(CliHelper.run())
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/cli.py", line 129, in run
    app.run()
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py", line 415, in run
    self.patch_sources(sources)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py", line 310, in patch_sources
    **self.kwargs)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 244, in patch
    return self._tool.run_patch(old_dir, new_dir, patches, **kwargs)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 205, in run_patch
    return cls._git_rebase()
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 130, in _git_rebase
    patch_name = cls.git_helper.get_unapplied_patch(cls.output_data)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 569, in get_unapplied_patch
    lines = [x for x in output if x.startswith("Patch failed at")]
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 569, in <listcomp>
    lines = [x for x in output if x.startswith("Patch failed at")]
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
it seems to work with Python2

**Comment by phracek** [comment]
This could be solved by this commit https://github.com/phracek/rebase-helper/commit/1759b3cb5a03c7402a4e56cadb6b03c15f56e81a. (rebasehelper/utils.py)

If it is not solved than please reopen it again.
