### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)

### ISSUE THREAD

**Issue by thozza** [phracek/rebase-helper#94]
running rebase-helper for wget ends with traceback:

```
$ python2 ~/devel/projects/rebase-helper/rebase-helper.py 1.16.3
Results directory 'rebase-helper-results' exists, removing it
Workspace directory 'rebase-helper-workspace' exists, removing it
Applying patch 'wget-rh-modified.patch' to 'wget-1.16.2'
Applying patch 'wget-1.16.1-path.patch' to 'wget-1.16.2'
Applying patch 'wget-1.16-dont-run-failing-test.patch' to 'wget-1.16.2'
Rebase operation is ongoing...
Traceback (most recent call last):
  File "/home/thozza/devel/projects/rebase-helper/rebase-helper.py", line 28, in <module>
    sys.exit(CliHelper.run())
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/cli.py", line 129, in run
    app.run()
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py", line 415, in run
    self.patch_sources(sources)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py", line 310, in patch_sources
    **self.kwargs)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 244, in patch
    return self._tool.run_patch(old_dir, new_dir, patches, **kwargs)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 205, in run_patch
    return cls._git_rebase()
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/patch_helper.py", line 135, in _git_rebase
    ret_code = cls.git_helper.command_diff('HEAD', output_file=base_name)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 656, in command_diff
    ret_code = self._call_git_command(cmd, output_file=output_file)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 497, in _call_git_command
    output=output)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 180, in run_subprocess_cwd
    return ProcessHelper.run_subprocess_cwd_env(cmd, cwd=cwd, input=input, output=output, shell=shell)
  File "/home/thozza/devel/projects/rebase-helper/rebasehelper/utils.py", line 282, in run_subprocess_cwd_env
    out_file.write(line.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)
```
 debug log:
```
2015-03-10 14:09:00,342 DEBUG	specfile.py:134 _update_data: Updating the extra version
2015-03-10 14:09:00,343 DEBUG	specfile.py:799 extract_version_from_archive_name: Extracting version from 'wget-1.16.2.tar.xz' using 'wget-%{version}.tar.xz'
2015-03-10 14:09:00,343 DEBUG	specfile.py:807 extract_version_from_archive_name: Extracting version using regex 'wget-([.0-9]+\w*).tar.xz'
2015-03-10 14:09:00,343 DEBUG	specfile.py:812 extract_version_from_archive_name: Extracted version '1.16.2'
2015-03-10 14:09:00,343 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.2'
2015-03-10 14:09:00,343 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.2' and extra string ''
2015-03-10 14:09:00,393 DEBUG	specfile.py:134 _update_data: Updating the extra version
2015-03-10 14:09:00,393 DEBUG	specfile.py:799 extract_version_from_archive_name: Extracting version from 'wget-1.16.2.tar.xz' using 'wget-%{version}.tar.xz'
2015-03-10 14:09:00,393 DEBUG	specfile.py:807 extract_version_from_archive_name: Extracting version using regex 'wget-([.0-9]+\w*).tar.xz'
2015-03-10 14:09:00,393 DEBUG	specfile.py:812 extract_version_from_archive_name: Extracted version '1.16.2'
2015-03-10 14:09:00,394 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.2'
2015-03-10 14:09:00,394 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.2' and extra string ''
2015-03-10 14:09:00,394 DEBUG	application.py:138 _prepare_spec_objects: argument passed as a new source is a version
2015-03-10 14:09:00,394 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.3'
2015-03-10 14:09:00,394 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.3' and extra string ''
2015-03-10 14:09:00,394 DEBUG	specfile.py:634 set_version: Updating version in SPEC from '1.16.2' with '1.16.3'
2015-03-10 14:09:00,394 DEBUG	specfile.py:543 _write_spec_file_to_disc: Writing SPEC file '/home/thozza/devel/fedora/wget/rebase-helper-results/wget.spec' to the disc
2015-03-10 14:09:00,418 DEBUG	specfile.py:134 _update_data: Updating the extra version
2015-03-10 14:09:00,418 DEBUG	specfile.py:799 extract_version_from_archive_name: Extracting version from 'wget-1.16.3.tar.xz' using 'wget-%{version}.tar.xz'
2015-03-10 14:09:00,418 DEBUG	specfile.py:807 extract_version_from_archive_name: Extracting version using regex 'wget-([.0-9]+\w*).tar.xz'
2015-03-10 14:09:00,418 DEBUG	specfile.py:812 extract_version_from_archive_name: Extracted version '1.16.3'
2015-03-10 14:09:00,418 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.3'
2015-03-10 14:09:00,419 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.3' and extra string ''
2015-03-10 14:09:00,419 DEBUG	specfile.py:655 set_extra_version: Updating extra version in SPEC to ''
2015-03-10 14:09:00,420 DEBUG	specfile.py:578 set_release_number: Changing release line to 'Release: 1%{?dist}'
2015-03-10 14:09:00,420 DEBUG	specfile.py:543 _write_spec_file_to_disc: Writing SPEC file '/home/thozza/devel/fedora/wget/rebase-helper-results/wget.spec' to the disc
2015-03-10 14:09:00,443 DEBUG	specfile.py:134 _update_data: Updating the extra version
2015-03-10 14:09:00,443 DEBUG	specfile.py:799 extract_version_from_archive_name: Extracting version from 'wget-1.16.3.tar.xz' using 'wget-%{version}.tar.xz'
2015-03-10 14:09:00,443 DEBUG	specfile.py:807 extract_version_from_archive_name: Extracting version using regex 'wget-([.0-9]+\w*).tar.xz'
2015-03-10 14:09:00,443 DEBUG	specfile.py:812 extract_version_from_archive_name: Extracted version '1.16.3'
2015-03-10 14:09:00,444 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.3'
2015-03-10 14:09:00,444 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.3' and extra string ''
2015-03-10 14:09:00,445 DEBUG	specfile.py:543 _write_spec_file_to_disc: Writing SPEC file '/home/thozza/devel/fedora/wget/rebase-helper-results/wget.spec' to the disc
2015-03-10 14:09:00,467 DEBUG	specfile.py:134 _update_data: Updating the extra version
2015-03-10 14:09:00,468 DEBUG	specfile.py:799 extract_version_from_archive_name: Extracting version from 'wget-1.16.3.tar.xz' using 'wget-%{version}.tar.xz'
2015-03-10 14:09:00,468 DEBUG	specfile.py:807 extract_version_from_archive_name: Extracting version using regex 'wget-([.0-9]+\w*).tar.xz'
2015-03-10 14:09:00,468 DEBUG	specfile.py:812 extract_version_from_archive_name: Extracted version '1.16.3'
2015-03-10 14:09:00,468 DEBUG	specfile.py:771 split_version_string: Splitting string '1.16.3'
2015-03-10 14:09:00,468 DEBUG	specfile.py:777 split_version_string: Divided version '1.16.3' and extra string ''
2015-03-10 14:09:00,468 WARNING	application.py:225 _check_workspace_dir: Workspace directory 'rebase-helper-workspace' exists, removing it
2015-03-10 14:09:00,468 DEBUG	application.py:216 _delete_workspace_dir: Removing the workspace directory '/home/thozza/devel/fedora/wget/rebase-helper-workspace'
2015-03-10 14:09:00,557 DEBUG	archive.py:182 extract: Extracting '/home/thozza/devel/fedora/wget/wget-1.16.2.tar.xz' into '/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources'
2015-03-10 14:09:01,003 DEBUG	archive.py:182 extract: Extracting '/home/thozza/devel/fedora/wget/wget-1.16.3.tar.xz' into '/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources'
2015-03-10 14:09:01,552 DEBUG	patch_helper.py:243 patch: Patching source by patch tool git
2015-03-10 14:09:01,552 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'init', '/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce18>, shell=False
2015-03-10 14:09:01,558 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:01,558 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '.'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce18>, shell=False
2015-03-10 14:09:02,093 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:02,093 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'commit', '-m', 'Initial Commit'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce18>, shell=False
2015-03-10 14:09:02,200 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:02,204 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'init', '/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources/wget-1.16.3'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources/wget-1.16.3, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce60>, shell=False
2015-03-10 14:09:02,210 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:02,210 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '.'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources/wget-1.16.3, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce60>, shell=False
2015-03-10 14:09:02,771 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:02,772 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'commit', '-m', 'Initial Commit'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources/wget-1.16.3, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0ce60>, shell=False
2015-03-10 14:09:02,878 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:02,881 INFO	patch_helper.py:172 apply_old_patches: Applying patch 'wget-rh-modified.patch' to 'wget-1.16.2'
2015-03-10 14:09:02,882 DEBUG	patch_helper.py:88 apply_patch: Applying patch with am
2015-03-10 14:09:02,882 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-rh-modified.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:02,966 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 1
2015-03-10 14:09:02,966 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am', '--abort'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-rh-modified.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,012 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,013 DEBUG	patch_helper.py:93 apply_patch: Applying patch with git am failed.
2015-03-10 14:09:03,013 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'apply'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-rh-modified.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,029 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,030 DEBUG	patch_helper.py:157 commit_patch: Commit patch
2015-03-10 14:09:03,030 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '--all'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,072 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,072 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'commit', '-m', 'Patch: wget-rh-modified.patch'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:03,133 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,133 INFO	patch_helper.py:172 apply_old_patches: Applying patch 'wget-1.16.1-path.patch' to 'wget-1.16.2'
2015-03-10 14:09:03,133 DEBUG	patch_helper.py:88 apply_patch: Applying patch with am
2015-03-10 14:09:03,134 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16.1-path.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,220 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 1
2015-03-10 14:09:03,221 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am', '--abort'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16.1-path.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,285 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,285 DEBUG	patch_helper.py:93 apply_patch: Applying patch with git am failed.
2015-03-10 14:09:03,285 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'apply'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16.1-path.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,294 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,295 DEBUG	patch_helper.py:157 commit_patch: Commit patch
2015-03-10 14:09:03,295 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '--all'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,317 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,317 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'commit', '-m', 'Patch: wget-1.16.1-path.patch'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:03,344 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,344 INFO	patch_helper.py:172 apply_old_patches: Applying patch 'wget-1.16-dont-run-failing-test.patch' to 'wget-1.16.2'
2015-03-10 14:09:03,344 DEBUG	patch_helper.py:88 apply_patch: Applying patch with am
2015-03-10 14:09:03,344 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16-dont-run-failing-test.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,399 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 1
2015-03-10 14:09:03,399 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'am', '--abort'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16-dont-run-failing-test.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,440 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,440 DEBUG	patch_helper.py:93 apply_patch: Applying patch with git am failed.
2015-03-10 14:09:03,440 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'apply'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=/home/thozza/devel/fedora/wget/wget-1.16-dont-run-failing-test.patch, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,445 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,445 DEBUG	patch_helper.py:157 commit_patch: Commit patch
2015-03-10 14:09:03,445 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '--all'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,456 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,457 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'commit', '-m', 'Patch: wget-1.16-dont-run-failing-test.patch'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cf80>, shell=False
2015-03-10 14:09:03,472 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,472 INFO	patch_helper.py:114 _git_rebase: Rebase operation is ongoing...
2015-03-10 14:09:03,473 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'remote', 'add', 'new_upstream', '/home/thozza/devel/fedora/wget/rebase-helper-workspace/new_sources/wget-1.16.3'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:03,476 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:03,476 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'fetch', 'new_upstream'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:04,417 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:04,417 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'log', '--pretty=oneline'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:04,421 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:09:04,421 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'rebase', '--onto', 'new_upstream/master', '3a9b4831ada97c169c24d3384326474e8bcb8138', '4ab63e9eba94b81962002342f3ca29c5295dc32f'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:09:04,870 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 1
2015-03-10 14:09:04,870 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'mergetool'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:11:44,244 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:11:44,245 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'add', '--all'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=<StringIO.StringIO instance at 0x7f199fe0cbd8>, shell=False
2015-03-10 14:11:44,258 DEBUG	utils.py:302 run_subprocess_cwd_env: subprocess exited with return code 0
2015-03-10 14:11:44,259 DEBUG	utils.py:218 run_subprocess_cwd_env: cmd=['git', 'diff', 'HEAD'], cwd=/home/thozza/devel/fedora/wget/rebase-helper-workspace/old_sources/wget-1.16.2, env=None, input=None, output=/home/thozza/devel/fedora/wget/rebase-helper-results/wget-rh-modified.patch, shell=False
```

**Comment by phracek** [comment]
How did you execute rebase-helper? Did you use a special terminal?
I would like to reproduce it.

**Comment by phracek** [comment]
The issues is fixed by commit https://github.com/phracek/rebase-helper/commit/1759b3cb5a03c7402a4e56cadb6b03c15f56e81a#diff-fe3e3d5f4c143113b3837700625080c8R292 Especially in rebasehelper/utils.py line row 293.

If problem still persist then please provide a reproducer.
