### ISSUE TITLE
another unicode traceback

### ISSUE THREAD

**Issue by pavlix** [phracek/rebase-helper#96]
Right at the start of rebase-helper.

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/rebase-helper", line 9, in <module>
    load_entry_point('rebasehelper==0.5.0', 'console_scripts', 'rebase-helper')()
  File "/usr/lib64/python2.7/site-packages/rebasehelper/cli.py", line 129, in run
    app.run()
  File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 404, in run
    self.patch_sources(sources)
  File "/usr/lib64/python2.7/site-packages/rebasehelper/application.py", line 294, in patch_sources
    self.rebase_spec_file.update_changelog(self.rebase_spec_file.get_new_log(git_helper))
  File "/usr/lib64/python2.7/site-packages/rebasehelper/specfile.py", line 924, in get_new_log
    ver=self.get_version()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0160' in position 6: ordinal not in range(128)

**Comment by phracek** [comment]
Just for information how did you execute rebase-helper?
Could you please provide information like what was an environment?
Terminal etc.?

**Comment by phracek** [comment]
If problem still occurs please write a scenario how to simulate it.
